/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ThankYouSonKimLoaiRouteImport } from './routes/thank-you-son-kim-loai'
import { Route as IndexRouteImport } from './routes/index'

const ThankYouSonKimLoaiRoute = ThankYouSonKimLoaiRouteImport.update({
  id: '/thank-you-son-kim-loai',
  path: '/thank-you-son-kim-loai',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/thank-you-son-kim-loai': typeof ThankYouSonKimLoaiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/thank-you-son-kim-loai': typeof ThankYouSonKimLoaiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/thank-you-son-kim-loai': typeof ThankYouSonKimLoaiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/thank-you-son-kim-loai'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/thank-you-son-kim-loai'
  id: '__root__' | '/' | '/thank-you-son-kim-loai'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ThankYouSonKimLoaiRoute: typeof ThankYouSonKimLoaiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/thank-you-son-kim-loai': {
      id: '/thank-you-son-kim-loai'
      path: '/thank-you-son-kim-loai'
      fullPath: '/thank-you-son-kim-loai'
      preLoaderRoute: typeof ThankYouSonKimLoaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ThankYouSonKimLoaiRoute: ThankYouSonKimLoaiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
